name: Super-Linter Check

on:
  push:
    branches-ignore: [master]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master]

permissions:
  contents: read
  issues: write 

jobs:
  # ==== FIRST JOB: CHECKING WITH SUPER-LINTER ====
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    outputs:
      # output-file: ${{ steps.save-output.outputs.output-file }}
      test-output: ${{ steps.save-output.outputs.test-output }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.10.1
        # continue-on-error: true
        id: super-linter-section
        env:
          VALIDATE_ALL_CODEBASE: true
          # VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_PYTHON_BLACK: true
          # VALIDATE_HTML: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save Linter Output
        id: save-output
        # run: echo "output-file=$(echo ${{ steps.super-linter-section.outputs.stdout }})" >> $GITHUB_OUTPUT
        run: echo "test-output=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      
      - name: Save Linter Output 2
        run: echo "test-output=$(echo $RANDOM)" >> .github/my-outputs/output-file.txt

      - name: Upload Linter Output
        uses: actions/upload-artifact@v3
        with:
          name: linter-output
          path: outputs

  # ==== SECOND JOB: REPORTING ISSUES ====
  report:
    needs: build
    if: failure() 
    name: Create Issue if Error
    runs-on: ubuntu-latest
    steps:
      - name: Output of test-output
        run: echo "${{ needs.build.outputs.test-output }}"
      
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}