name: Lint Code Base

on:
  push:
    branches-ignore: [master]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    outputs:
      output-file: ${{ steps.publish.outputs.output-file }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.10.1
        continue-on-error: true
        id: super-linter-section
        env:
          VALIDATE_ALL_CODEBASE: true
          # VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_PYTHON_BLACK: true
          # VALIDATE_HTML: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save Linter Output
        id: save-output
        run: echo "${{ steps.super-linter-section.outputs.* }}" >> $GITHUB_OUTPUT
        # run: find outputs/*.txt -type f -execdir echo '::set-output name=output-file::{}' ';'

      - name: Upload Linter Output
        uses: actions/upload-artifact@v3
        with:
          name: linter-output
          path: outputs

  report:
    needs: build
    # if: failure() 
    name: Create Issue if Error
    runs-on: ubuntu-latest
    steps:
      # - name: Get build artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: dist-files
      # - name: Output contents
      #   run: ls
      - name: 
        run: echo "${{ needs.build.outputs.output-file }}"
      # - name: Deploy
      #   run: echo "Deploying..."
      - name: Get repository
      - uses: actions/checkout@v3
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Simple test issue
          body: my new issue